# Generated by Django 4.2.2 on 2023-07-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ard', models.CharField(max_length=250)),
                ('vv', models.CharField(max_length=250)),
                ('mail', models.EmailField(max_length=254)),
                ('assword', models.CharField(max_length=250)),
            ],
        ),
    ]
