# Generated by Django 4.2.2 on 2023-07-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_prem'),
    ]

    operations = [
        migrations.CreateModel(
            name='pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rd', models.CharField(max_length=250)),
                ('v', models.CharField(max_length=250)),
                ('ail', models.EmailField(max_length=254)),
                ('ssword', models.CharField(max_length=250)),
            ],
        ),
    ]
